CREATE TABLE IF NOT EXISTS rsm_users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(180) NOT NULL,
  nik VARCHAR(80) NULL,
  username VARCHAR(100) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('senior','koordinator','staff') NOT NULL DEFAULT 'staff',
  jabatan VARCHAR(120) NOT NULL,
  regional VARCHAR(120) NULL,
  area VARCHAR(40) NULL,
  campus_name VARCHAR(180) NULL,
  must_change_password TINYINT(1) NOT NULL DEFAULT 1,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_rsm_users_username (username),
  INDEX idx_rsm_users_role (role),
  INDEX idx_rsm_users_regional (regional),
  INDEX idx_rsm_users_area (area)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rsm_reports (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  area VARCHAR(40) NOT NULL,
  report_type ENUM('marketing','ads','other') NOT NULL,
  report_date DATE NOT NULL,
  user_id INT NULL,
  partner_campus_id INT NULL,
  wilayah VARCHAR(120) NOT NULL,
  unit_name VARCHAR(180) NOT NULL,
  staff_name VARCHAR(180) NOT NULL,
  created_by_name VARCHAR(180) NULL,
  created_by_role VARCHAR(40) NOT NULL,
  status VARCHAR(60) NOT NULL DEFAULT 'Draft',
  title VARCHAR(220) NOT NULL,
  activity_kind VARCHAR(120) NULL,
  location_name VARCHAR(220) NULL,
  target_text TEXT NULL,
  result_text TEXT NULL,
  leads_count INT UNSIGNED NOT NULL DEFAULT 0,
  closing_count INT UNSIGNED NOT NULL DEFAULT 0,
  notes TEXT NULL,
  platform VARCHAR(120) NULL,
  campaign_name VARCHAR(220) NULL,
  ad_goal VARCHAR(80) NULL,
  budget_requested DECIMAL(15,2) NOT NULL DEFAULT 0,
  budget_approved DECIMAL(15,2) NOT NULL DEFAULT 0,
  realization_amount DECIMAL(15,2) NOT NULL DEFAULT 0,
  cpl DECIMAL(15,2) NOT NULL DEFAULT 0,
  campaign_link VARCHAR(500) NULL,
  category VARCHAR(120) NULL,
  obstacle_text TEXT NULL,
  follow_up_text TEXT NULL,
  attachment_path VARCHAR(500) NULL,
  revision_note TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_rsm_reports_area_type (area, report_type),
  INDEX idx_rsm_reports_status (status),
  INDEX idx_rsm_reports_date (report_date),
  INDEX idx_rsm_reports_staff (staff_name),
  INDEX idx_rsm_reports_user (user_id),
  INDEX idx_rsm_reports_campus (partner_campus_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rsm_activity_logs (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  report_id INT UNSIGNED NULL,
  area VARCHAR(40) NOT NULL,
  actor_role VARCHAR(40) NOT NULL,
  actor_name VARCHAR(180) NULL,
  action_name VARCHAR(120) NOT NULL,
  old_status VARCHAR(60) NULL,
  new_status VARCHAR(60) NULL,
  note TEXT NULL,
  ip_address VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_rsm_logs_report (report_id),
  INDEX idx_rsm_logs_area (area),
  CONSTRAINT fk_rsm_logs_report
    FOREIGN KEY (report_id) REFERENCES rsm_reports(id)
    ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rsm_ad_leads (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  report_id INT UNSIGNED NOT NULL,
  lead_name VARCHAR(180) NULL,
  whatsapp VARCHAR(80) NULL,
  email VARCHAR(180) NULL,
  campus_name VARCHAR(180) NULL,
  major_name VARCHAR(180) NULL,
  origin_city VARCHAR(120) NULL,
  follow_up_result TEXT NULL,
  progress_status VARCHAR(120) NULL,
  closing_status VARCHAR(80) NULL,
  closing_update VARCHAR(180) NULL,
  notes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_rsm_ad_leads_report (report_id),
  CONSTRAINT fk_rsm_ad_leads_report
    FOREIGN KEY (report_id) REFERENCES rsm_reports(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
